### ISSUE TITLE
Testing time for the inference stage

### ISSUE THREAD

**Issue by geekJZY** [carrierlxk/GraphMemVOS#6]
Hi,

I am very interested in this work and I am trying to test its performance. 
I successfully run the code, but the speed I got is about 1s/frame on the V100 GPU, which is far slower than what the paper reported. Do you have any idea why it would be like this.

Thanks.

**Comment by lzozo95** [comment]
HI,

I'm so sorry that this comment is not about your query. I want to ask you a question.
How can you download the normal weight file and how to use it? Isn't there any error?

Thanks.

**Comment by geekJZY** [comment]
> HI,
> 
> I'm so sorry that this comment is not about your query. I want to ask you a question.
> How can you download the normal weight file and how to use it? Isn't there any error?
> 
> Thanks.

I just download without unzipping. The torch.load can directly read it.

**Comment by pingjun18-li** [comment]
> > HI,
> > I'm so sorry that this comment is not about your query. I want to ask you a question.
> > How can you download the normal weight file and how to use it? Isn't there any error?
> > Thanks.
> 
> I just download without unzipping. The torch.load can directly read it.

I have download the weight, but when i load it , it print the error as below:
>>> import torch
>>> torch.load("/data/VOS/GraphMemVOS-master/workspace_STM_alpha/main_runfile_graph_memory.pth.tar")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'utils.stats'
or can anyone who can read the weight to save it to nomally .pth but npt .pth.tar? thank u very much
